# permissions for end users to edit dledgerbrokers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dledgerbroker-editor-role
rules:
- apiGroups:
  - rocketmq.daocloud.io
  resources:
  - dledgerbrokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocketmq.daocloud.io
  resources:
  - dledgerbrokers/status
  verbs:
  - get
