# permissions for end users to view nameservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nameserver-viewer-role
rules:
- apiGroups:
  - rocketmq.daocloud.io
  resources:
  - nameservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rocketmq.daocloud.io
  resources:
  - nameservers/status
  verbs:
  - get
